import { afterEach, describe, expect, it, vi } from 'vitest';
import { createTvRemoteStatusPublisher } from './tv-remote-status-publisher';
import type { TvRemotePlaybackSnapshot } from '@home-music/shared/tv-remote';
const initial: TvRemotePlaybackSnapshot = { trackId: null, title: null, artist: null, playing: false, currentTime: 0, duration: 0, updatedAt: '2026-09-14T00:00:00Z', crossfadeSeconds: 0, lastAppliedCrossfadeCommandId: 0 };
afterEach(() => vi.useRealTimers());
describe('serialized TV status publisher', () => {
  it('coalesces commands and heartbeats behind a slow PUT and publishes the latest coherent pair', async () => {
    vi.useFakeTimers();
    let current = initial;
    let release!: () => void;
    const send = vi.fn().mockImplementationOnce(() => new Promise<void>(resolve => { release = resolve; })).mockResolvedValue(undefined);
    const publisher = createTvRemoteStatusPublisher(() => current, send, vi.fn());
    publisher.request(true);
    await vi.advanceTimersByTimeAsync(0);
    current = { ...initial, crossfadeSeconds: 3, lastAppliedCrossfadeCommandId: 2 };
    publisher.request();
    current = { ...initial, crossfadeSeconds: 5, lastAppliedCrossfadeCommandId: 3 };
    publisher.request(true);
    await vi.advanceTimersByTimeAsync(2000);
    expect(send).toHaveBeenCalledTimes(1);
    release();
    await vi.advanceTimersByTimeAsync(0);
    expect(send).toHaveBeenCalledTimes(2);
    expect(send).toHaveBeenLastCalledWith(current);
    publisher.request();
    await vi.advanceTimersByTimeAsync(1000);
    expect(send).toHaveBeenCalledTimes(2);
    publisher.stop();
  });
  it('does not acknowledge failed sends or retry in a tight loop, and invalidates old sessions', async () => {
    vi.useFakeTimers();
    const error = vi.fn();
    const send = vi.fn().mockRejectedValueOnce(new Error('offline')).mockResolvedValue(undefined);
    const publisher = createTvRemoteStatusPublisher(() => initial, send, error);
    publisher.request();
    await vi.advanceTimersByTimeAsync(10000);
    expect(send).toHaveBeenCalledTimes(1);
    expect(error).toHaveBeenCalledOnce();
    publisher.request();
    await vi.advanceTimersByTimeAsync(0);
    expect(send).toHaveBeenCalledTimes(2);
    publisher.request(true);
    publisher.stop();
    await vi.advanceTimersByTimeAsync(10000);
    expect(send).toHaveBeenCalledTimes(2);
  });
  it('ignores resolution of an old session while its PUT is pending', async () => {
    vi.useFakeTimers();
    let reject!: (error: Error) => void;
    const error = vi.fn();
    const send = vi.fn(() => new Promise<void>((_, fail) => { reject = fail; }));
    const publisher = createTvRemoteStatusPublisher(() => initial, send, error);
    publisher.request();
    await vi.advanceTimersByTimeAsync(0);
    publisher.request(true);
    publisher.stop();
    reject(new Error('late'));
    await vi.advanceTimersByTimeAsync(2000);
    expect(error).not.toHaveBeenCalled();
    expect(send).toHaveBeenCalledOnce();
  });
});
